#!/usr/bin/env python3
"""
STIL Template Generator (IEEE 1450 Compliant)
Generates STIL pattern files for DFT verification.

This module provides functionality to generate STIL (Standard Test Interface Language)
files compliant with IEEE 1450 standard for test pattern generation and verification.
"""

import os
from datetime import datetime
from typing import Dict, List, Optional, Tuple
from dataclasses import dataclass, field


@dataclass
class STILSignal:
    """Represents a signal in STIL format."""
    name: str
    direction: str  # 'In', 'Out', 'InOut', 'Supply'
    signal_type: str  # 'Digital', 'Analog', 'Power', 'Ground'
    description: Optional[str] = None


@dataclass
class STILPattern:
    """Represents a test pattern vector."""
    vector_id: str
    signals: Dict[str, str]  # signal_name -> value ('0', '1', 'X', 'Z', 'L', 'H', 'P', 'D')
    comment: Optional[str] = None


@dataclass
class STILTiming:
    """Represents timing information for STIL patterns."""
    period: float  # in nanoseconds
    waveforms: Dict[str, List[Tuple[str, float]]]  # waveform_name -> [(edge_type, time), ...]
    # edge_type: 'C', 'D', 'U', 'Z', 'V'


class STILTemplateGenerator:
    """
    IEEE 1450 compliant STIL file generator.
    
    Generates STIL files with proper header, signal definitions, timing,
    patterns, and procedures for DFT verification.
    """
    
    def __init__(self, output_file: str):
        """
        Initialize STIL generator.
        
        Args:
            output_file: Path to output STIL file
        """
        self.output_file = output_file
        self.signals: List[STILSignal] = []
        self.patterns: List[STILPattern] = []
        self.timing: Optional[STILTiming] = None
        self.procedures: Dict[str, str] = {}
        
    def add_signal(self, signal: STILSignal):
        """Add a signal definition to the STIL file."""
        self.signals.append(signal)
        
    def add_pattern(self, pattern: STILPattern):
        """Add a test pattern to the STIL file."""
        self.patterns.append(pattern)
        
    def set_timing(self, timing: STILTiming):
        """Set timing information for patterns."""
        self.timing = timing
        
    def add_procedure(self, name: str, procedure_code: str):
        """Add a procedure definition."""
        self.procedures[name] = procedure_code
        
    def generate_header(self) -> str:
        """Generate STIL file header with metadata."""
        header = f"""STIL 1.0;

// Generated by DFT-STIL Verification Framework
// Generation Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
// IEEE 1450 Compliant STIL File

"""
        return header
        
    def generate_signals(self) -> str:
        """Generate signal definitions section."""
        if not self.signals:
            return ""
            
        signal_def = "Signals {\n"
        for signal in self.signals:
            signal_def += f'    "{signal.name}" {signal.direction} {signal.signal_type}'
            if signal.description:
                signal_def += f' // {signal.description}'
            signal_def += ";\n"
        signal_def += "}\n\n"
        return signal_def
        
    def generate_timing(self) -> str:
        """Generate timing section."""
        if not self.timing:
            return ""
            
        timing_def = f"""Timing {
    WaveformTable "default_wft" {{
        Period {self.timing.period}ns;
"""
        for wf_name, edges in self.timing.waveforms.items():
            timing_def += f'        Wave "{wf_name}" {{'
            for edge_type, time in edges:
                timing_def += f' {edge_type} {time}ns;'
            timing_def += " }\n"
        timing_def += "    }\n}\n\n"
        return timing_def
        
    def generate_patterns(self) -> str:
        """
        Generate pattern section.

        NOTE: The project STIL validator (`stil_utils/stil_validator.py`) expects
        vector syntax of the form:
            V { <vector_chars> };
        where the vector width matches the declared signal ordering.

        To stay IEEE-1450-friendly and validator-compatible, we:
        - Emit a `PatternExec` block that references patterns by name
        - Emit a `Patterns` section with `Pattern "<name>" { V { ... }; }`
        - Emit vectors as a single concatenated string in the order of the
          Signals section (as is typical with STIL WFT usage)
        """
        if not self.patterns:
            return ""

        # Determine canonical signal order (Signals block order)
        signal_order = [s.name for s in self.signals]
        if not signal_order:
            # Fallback: stable ordering from union of all patterns' signal keys.
            # Empty dict {} is falsy — do not use `not p.signals` or we suppress
            # generation when the first pattern legitimately has no entries yet.
            keys_set = set()
            for p in self.patterns:
                keys_set.update(p.signals.keys())
            signal_order = sorted(keys_set)

        # PatternExec references patterns by name
        out = "PatternExec {\n"
        out += "    PatList {\n"
        for p in self.patterns:
            out += f'        "{p.vector_id}";\n'
        out += "    }\n"
        out += "}\n\n"

        # Patterns section
        out += "Patterns {\n"
        for p in self.patterns:
            out += f'    Pattern "{p.vector_id}" {{\n'
            # Build vector string in signal_order
            vec_chars = []
            for sig in signal_order:
                v = p.signals.get(sig, "X")
                # STIL vector chars typically: 0/1/X/Z (also L/H etc). Keep as-is, default X.
                vec_chars.append(v)
            vec = "".join(vec_chars)
            if p.comment:
                out += f'        // {p.comment}\n'
            out += f"        V {{ {vec} }};\n"
            out += "    }\n"
        out += "}\n\n"
        return out
        
    def generate_procedures(self) -> str:
        """Generate procedure definitions."""
        if not self.procedures:
            return ""
            
        proc_def = "Procedures {\n"
        for name, code in self.procedures.items():
            proc_def += f'    "{name}" {{\n'
            proc_def += f"        {code}\n"
            proc_def += "    }\n"
        proc_def += "}\n\n"
        return proc_def
        
    def generate(self) -> str:
        """
        Generate complete STIL file content.
        
        Returns:
            Complete STIL file as string
        """
        stil_content = self.generate_header()
        stil_content += self.generate_signals()
        stil_content += self.generate_timing()
        stil_content += self.generate_procedures()
        stil_content += self.generate_patterns()
        
        return stil_content
        
    def write_file(self):
        """Write generated STIL content to file."""
        content = self.generate()
        with open(self.output_file, 'w') as f:
            f.write(content)
        print(f"STIL file generated: {self.output_file}")


def create_example_stil(output_file: str = "examples/example_pattern.stil"):
    """
    Create an example STIL file for demonstration.
    
    Args:
        output_file: Path to output file
    """
    generator = STILTemplateGenerator(output_file)
    
    # Add signals
    generator.add_signal(STILSignal("TCK", "In", "Digital", "JTAG Clock"))
    generator.add_signal(STILSignal("TMS", "In", "Digital", "JTAG Mode Select"))
    generator.add_signal(STILSignal("TDI", "In", "Digital", "JTAG Data In"))
    generator.add_signal(STILSignal("TDO", "Out", "Digital", "JTAG Data Out"))
    generator.add_signal(STILSignal("TRST", "In", "Digital", "JTAG Reset"))
    
    # Add timing
    timing = STILTiming(
        period=100.0,  # 100ns period = 10MHz
        waveforms={
            "clk": [("C", 0), ("D", 50)],
            "data": [("C", 0), ("D", 20), ("U", 80)]
        }
    )
    generator.set_timing(timing)
    
    # Add patterns
    pattern1 = STILPattern(
        vector_id="vec_001",
        signals={"TCK": "0", "TMS": "0", "TDI": "0", "TDO": "X", "TRST": "1"},
        comment="Initial state"
    )
    generator.add_pattern(pattern1)
    
    pattern2 = STILPattern(
        vector_id="vec_002",
        signals={"TCK": "1", "TMS": "0", "TDI": "1", "TDO": "X", "TRST": "1"},
        comment="Shift data"
    )
    generator.add_pattern(pattern2)
    
    # Generate and write
    generator.write_file()


if __name__ == "__main__":
    import sys
    output = sys.argv[1] if len(sys.argv) > 1 else "examples/example_pattern.stil"
    create_example_stil(output)
