/**
 * STIL Subscriber
 * 
 * UVM subscriber that monitors transactions and generates STIL patterns.
 * Implements the UVM subscriber pattern to capture testbench activity
 * and convert it to IEEE 1450 compliant STIL format.
 */

class stil_subscriber extends uvm_subscriber#(jtag_transaction);
    
    `uvm_component_utils(stil_subscriber)
    
    // Configuration
    test_config cfg;
    
    // STIL pattern storage
    jtag_transaction pattern_queue[$];
    
    // File handle for STIL output
    int stil_file_handle;
    
    // Pattern counter
    int pattern_count = 0;
    
    // Constructor
    function new(string name = "stil_subscriber", uvm_component parent = null);
        super.new(name, parent);
    endfunction
    
    // Build phase
    function void build_phase(uvm_phase phase);
        super.build_phase(phase);
        
        if (!uvm_config_db#(test_config)::get(this, "", "cfg", cfg)) begin
            `uvm_warning("NO_CFG", "Failed to get test_config, using defaults")
        end
    endfunction
    
    // Connect phase
    function void connect_phase(uvm_phase phase);
        super.connect_phase(phase);
    endfunction
    
    // Start of simulation
    function void start_of_simulation_phase(uvm_phase phase);
        super.start_of_simulation_phase(phase);
        
        if (cfg != null && cfg.stil_enable_generation) begin
            open_stil_file();
            write_stil_header();
        end
    endfunction
    
    // Write phase - called when simulation ends
    function void write(jtag_transaction t);
        if (cfg != null && cfg.stil_enable_generation) begin
            pattern_queue.push_back(t);
            pattern_count++;
            
            // Write pattern to STIL file
            write_stil_pattern(t);
        end
    endfunction
    
    // Extract phase - finalize STIL file
    function void extract_phase(uvm_phase phase);
        super.extract_phase(phase);
        
        if (cfg != null && cfg.stil_enable_generation) begin
            write_stil_footer();
            close_stil_file();
            `uvm_info("STIL_SUB", $sformatf("Generated %0d STIL patterns", pattern_count), UVM_MEDIUM)
        end
    endfunction
    
    // Open STIL output file
    function void open_stil_file();
        string filename;
        if (cfg != null) begin
            filename = cfg.stil_output_file;
        end else begin
            filename = "output.stil";  // Default filename
        end
        stil_file_handle = $fopen(filename, "w");
        if (stil_file_handle == 0) begin
            `uvm_fatal("STIL_SUB", $sformatf("Failed to open STIL file: %s", filename))
        end
        `uvm_info("STIL_SUB", $sformatf("Opened STIL file: %s", filename), UVM_MEDIUM)
    endfunction
    
    // Write STIL file header
    function void write_stil_header();
        $fwrite(stil_file_handle, "STIL 1.0;\n\n");
        $fwrite(stil_file_handle, "// Generated by DFT-STIL Verification Framework\n");
        $fwrite(stil_file_handle, "// IEEE 1450 Compliant STIL File\n\n");
        
        // Signal definitions
        $fwrite(stil_file_handle, "Signals {\n");
        $fwrite(stil_file_handle, '    "TCK" In Digital;\n');
        $fwrite(stil_file_handle, '    "TMS" In Digital;\n');
        $fwrite(stil_file_handle, '    "TDI" In Digital;\n');
        $fwrite(stil_file_handle, '    "TDO" Out Digital;\n');
        $fwrite(stil_file_handle, '    "TRST" In Digital;\n');
        $fwrite(stil_file_handle, "}\n\n");
        
        // Timing section
        $fwrite(stil_file_handle, "Timing {\n");
        $fwrite(stil_file_handle, $sformatf("    WaveformTable \"default_wft\" {\n"));
        int period_ns = (cfg != null) ? cfg.jtag_clock_period_ns : 100;  // Default 100ns if cfg is null
        $fwrite(stil_file_handle, $sformatf("        Period %0dns;\n", period_ns));
        $fwrite(stil_file_handle, "    }\n");
        $fwrite(stil_file_handle, "}\n\n");
    endfunction
    
    // Write a single STIL pattern
    function void write_stil_pattern(jtag_transaction t);
        string vector_id = $sformatf("vec_%06d", pattern_count);
        
        $fwrite(stil_file_handle, $sformatf("    V \"%s\" TCK=%b TMS=%b TDI=%b TDO=%b TRST=1;\n",
                vector_id, 1, t.tms, t.tdi, t.tdo));
    endfunction
    
    // Write STIL file footer
    function void write_stil_footer();
        $fwrite(stil_file_handle, "\n// End of STIL file\n");
    endfunction
    
    // Close STIL file
    function void close_stil_file();
        $fclose(stil_file_handle);
        `uvm_info("STIL_SUB", "Closed STIL file", UVM_MEDIUM)
    endfunction

endclass
